export const API_URL = `${window.location.protocol}${'//api.nomoreparties.co'}`;
export const BEATFILM_URL = `${window.location.protocol}${'//api.nomoreparties.co/beatfilm-movies'}`;
export const BASE_URL = `${window.location.protocol}${'//api.films-explorer.nomoredomains.sbs'}`;
export const SHORT_MOVIE_DURATION = 40;
export const NAME_PATTERN = /([А-ЯЁа-яёa-z-\s]+)/ig;
export const EMAIL_PATTERN = /^([\w.%+-]+)@([\w-]+\.)+([\w]{2,})$/i;
export const NAME_ERROR_MESSAGE = 'Имя может содержать только кирилицу, латиницу, пробел или дефис!';
export const EMAIL_ERROR_MESSAGE = 'Введён некорректный email!';
export const PASSWORD_ERROR_MESSAGE = 'Пароль не должен быть короче шести символов!';
